# Generated by Django 2.1.3 on 2018-12-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_tempuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='role',
            field=models.IntegerField(),
        ),
    ]
